Added a new instruction
ANF-Studios/ANFuck pull request #1
Opened 2021-05-02 13:30 UTC by YeffyCodeGit

h

2021-05-02 13:38 UTC, ANF-Studios requested changes
You can work on those suggested changes and, also, please show me a preview of it being used.

2021-05-02 13:38 UTC, ANF-Studios commented on ANFuck/src/main.h
> +		if (!file.is_open()) throw std::runtime_error("Failed to open '" + filename + "'.");
There is no need for that. You have to keep in mind when contributing to open source projects that every maintainer has their own programming style and you should keep to that and keep it consistent.

2021-05-02 13:38 UTC, ANF-Studios commented on ANFuck/src/main.h
> +					else instructionStack.pop();
Revert these back as well please.

2021-05-02 13:38 UTC, ANF-Studios commented on ANFuck/src/main.h
> +					std::cout << *dataPtr;
Why are we printing a value?

2021-05-02 13:45 UTC, YeffyCodeGit commented on ANFuck/src/main.h
> +					std::cout << *dataPtr;
That was mostly for testing to make sure if it was working, ill remove it now

2021-05-03 09:49 UTC, YeffyCodeGit commented
h

2021-05-03 09:55 UTC, ANF-Studios commented
CI fails, compiler errors, code non-functional.

2021-05-03 10:18 UTC, ANF-Studios commented
Doesn't work as expected.
![image](https://user-images.githubusercontent.com/68814933/116865269-50644900-abd7-11eb-8dde-327ed06a90a0.png)

2021-05-03 10:30 UTC, ANF-Studios commented on ANFuck/src/main.cpp
> +    try
Bad formatting.

2021-05-03 10:30 UTC, ANF-Studios commented on ANFuck/src/main.h
> +					else
You added empty spaces again.

2021-05-03 10:30 UTC, ANF-Studios commented on ANFuck/src/main.h
> +
Unnecessary empty line

2021-05-03 10:55 UTC, ANF-Studios requested changes
I'm not really confident that this pull even accomplishes what it targets.

2021-05-03 10:55 UTC, ANF-Studios commented on ANFuck/src/main.h
> +					*dataPtr = *defaultDataPtr;
This doesn't work. Are you sure I'm not doing anything wrong?

2021-08-04 05:07 UTC, closed without merging

2021-09-26 20:14 UTC, ANF-Studios commented
@YeffyCodeGit, please do not just open and close issues.